{{- define "envify" -}}
{{- $prefix := index . 0 -}}
{{- $value := index . 1 -}}
{{- $root := index . 2 -}}
{{- if kindIs "map" $value -}}
  {{- range $k, $v := $value -}}
    {{- if $prefix -}}
        {{- template "envify" (list (printf "%s.%s" $prefix $k) $v $root) -}}
    {{- else -}}
        {{- template "envify" (list (printf "%s" $k) $v $root) -}}
    {{- end -}}
  {{- end -}}
{{- else -}}
{{ if contains "{{" (toString $value) -}}
{{ $prefix | indent 4 }}={{ tpl (toString $value) $root }}
{{ else -}}
{{ $prefix | indent 4 }}={{ $value }}
{{ end -}}
{{ end -}}
{{- end -}}
---
apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: {{ include "helm-props.fullname" . }}-configs
  labels:
    {{- include "helm-props.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.configuration }}
{{ $k | indent 2 }}: |
{{ tpl (toYaml $v) $ | indent 4 }}
{{- end }}
{{- range $k, $v := .Values.configurationProperties }}
{{ $k | indent 2 }}: |
{{ template "envify" (list "" $v $) }}
{{- end }}
{{- range $k, $v := .Values.configurationRaw }}
{{ $k | indent 2 }}: |
{{ tpl $v $ | indent 4 }}
{{- end }}
