{{- define "envify" -}}
{{- $prefix := index . 0 -}}
{{- $value := index . 1 -}}
{{- if kindIs "map" $value -}}
  {{- range $k, $v := $value -}}
    {{- if $prefix -}}
        {{- template "envify" (list (printf "%s.%s" $prefix $k) $v) -}}
    {{- else -}}
        {{- template "envify" (list (printf "%s" $k) $v) -}}
    {{- end -}}
  {{- end -}}
{{- else -}}
{{ $prefix | indent 4 }}={{ $value }}
{{ end -}}
{{- end -}}

apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: {{ include "helm-props.fullname" . }}
  labels:
    {{- include "helm-props.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.appConfigs }}
  {{ $k }}: |
{{ template "envify" (list "" $v)  }}
{{- end }}
